### ISSUE TITLE
Test failure depdending on initial state of homedir

### ISSUE THREAD

**Issue by wearpants** [EFForg/cryptobot-email#23] opened 2013-11-27 16:34 UTC
The following tests pass if `test/homedir` exist, but fail if it doesn't:
- test_encrypted_pubkey_included_attached_application_pgpkeys
- test_encrypted_pubkey_included_attached_text_plain
- test_encrypted_pubkey_included_inline

I have a patch (soon) that resolves indeterminacy (by rm'ing `test/homedir` before each test), but we'll still need to fix the underlying problem. I _think_ calling `GnuPG.gen_key` for each test should do the trick...

**Comment by wearpants** [comment] 2013-11-27 21:42
After playing around a bit, generating a new keypair on each test is _extremely_ slow (lack of entropy). Would a pre-generated `homedir_template` that gets copied fresh to `homedir` for each test work? Template would have a keypair for the bot, be checked into git, etc..

There is one test (`GnuPGTest.test_gen_key`) which needs to generate a new key; this should probably use a separate temporary homedir entirely

**Comment by micahflee** [comment] 2013-11-28 00:23
Actually, this is a duplicate of #18. I'm closing this one, but you can continue commenting in the other.

And I've noticed that keygen is really really slow. Anything to speed it up is welcome :).

**Closed as completed by micahflee** 2013-11-28 00:23 UTC
